package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRunReportsMissingDocumentation(t *testing.T) {
	root := t.TempDir()
	writeSource(t, root, "good.go", `// Package sample is documented.
package sample

// Good is documented.
type Good interface {
	// Run does work.
	Run()
}

// Exported is documented.
func Exported() {}
`)
	var stdout, stderr bytes.Buffer
	if code := run([]string{root}, &stdout, &stderr); code != 0 {
		t.Fatalf("run() = %d, stderr = %q", code, stderr.String())
	}
	if stdout.Len() != 0 {
		t.Fatalf("stdout = %q", stdout.String())
	}

	writeSource(t, root, "bad.go", `package sample

type Missing interface {
	Call()
}

func Undocumented() {}
`)
	stdout.Reset()
	stderr.Reset()
	if code := run([]string{root}, &stdout, &stderr); code != 1 {
		t.Fatalf("run() = %d, want 1", code)
	}
	for _, expected := range []string{
		"Missing: missing doc comment",
		"Missing.Call: missing doc comment",
		"Undocumented: missing doc comment",
	} {
		if !strings.Contains(stdout.String(), expected) {
			t.Errorf("stdout %q does not contain %q", stdout.String(), expected)
		}
	}
}

func TestAuditExcludesGeneratedTestsAndUnexportedReceivers(t *testing.T) {
	root := t.TempDir()
	writeSource(t, root, "doc.go", `// Package sample is documented.
package sample
`)
	writeSource(t, root, "generated.go", `// Code generated by test. DO NOT EDIT.
package sample

type Generated struct{}
`)
	writeSource(t, root, "sample_test.go", `package sample

func ExportedTestHelper() {}
`)
	writeSource(t, root, "internal.go", `package sample

type internal struct{}

func (internal) ExportedMethod() {}

type internalInterface interface {
	ExportedMethod()
}
`)
	findings, err := audit([]string{root})
	if err != nil {
		t.Fatal(err)
	}
	if len(findings) != 0 {
		t.Fatalf("findings = %#v", findings)
	}
}

func TestAuditAcceptsGroupedDeclarationComment(t *testing.T) {
	root := t.TempDir()
	writeSource(t, root, "sample.go", `// Package sample is documented.
package sample

// Public values.
const (
	First = 1
	Second = 2
)
`)
	findings, err := audit([]string{root})
	if err != nil {
		t.Fatal(err)
	}
	if len(findings) != 0 {
		t.Fatalf("findings = %#v", findings)
	}
}

func TestAuditReportsPackageComment(t *testing.T) {
	root := t.TempDir()
	writeSource(t, root, "sample.go", `package sample

// Value is documented.
const Value = 1
`)
	findings, err := audit([]string{root})
	if err != nil {
		t.Fatal(err)
	}
	if len(findings) != 1 || findings[0].symbol != "package sample" {
		t.Fatalf("findings = %#v", findings)
	}
}

func TestRunUsageAndParseErrors(t *testing.T) {
	var stdout, stderr bytes.Buffer
	if code := run(nil, &stdout, &stderr); code != 2 {
		t.Fatalf("run(nil) = %d, want 2", code)
	}
	if !strings.Contains(stderr.String(), "usage:") {
		t.Fatalf("stderr = %q", stderr.String())
	}

	root := t.TempDir()
	writeSource(t, root, "bad.go", "package")
	stdout.Reset()
	stderr.Reset()
	if code := run([]string{root}, &stdout, &stderr); code != 2 {
		t.Fatalf("run(parse error) = %d, want 2", code)
	}
	if !strings.Contains(stderr.String(), "doccheck:") {
		t.Fatalf("stderr = %q", stderr.String())
	}
}

func writeSource(t *testing.T, root, name, source string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(root, name), []byte(source), 0o600); err != nil {
		t.Fatal(err)
	}
}
