// Code generated by protocolgen v0.1.0; DO NOT EDIT.
// Source: Apache Fluss v0.9.1-incubating commit 6bf969f71af8d6f9cc37383ab89ae46a58b0e227.

package fmsg

import "google.golang.org/protobuf/proto"

type APIKey int16

const (
	APIKeyApiVersions                APIKey = 1000
	APIKeyCreateDatabase             APIKey = 1001
	APIKeyDropDatabase               APIKey = 1002
	APIKeyListDatabases              APIKey = 1003
	APIKeyDatabaseExists             APIKey = 1004
	APIKeyCreateTable                APIKey = 1005
	APIKeyDropTable                  APIKey = 1006
	APIKeyGetTableInfo               APIKey = 1007
	APIKeyListTables                 APIKey = 1008
	APIKeyListPartitionInfos         APIKey = 1009
	APIKeyTableExists                APIKey = 1010
	APIKeyGetTableSchema             APIKey = 1011
	APIKeyGetMetadata                APIKey = 1012
	APIKeyUpdateMetadata             APIKey = 1013
	APIKeyProduceLog                 APIKey = 1014
	APIKeyFetchLog                   APIKey = 1015
	APIKeyPutKv                      APIKey = 1016
	APIKeyLookup                     APIKey = 1017
	APIKeyNotifyLeaderAndIsr         APIKey = 1018
	APIKeyStopReplica                APIKey = 1019
	APIKeyAdjustIsr                  APIKey = 1020
	APIKeyListOffsets                APIKey = 1021
	APIKeyCommitKvSnapshot           APIKey = 1022
	APIKeyGetLatestKvSnapshots       APIKey = 1023
	APIKeyGetKvSnapshotMetadata      APIKey = 1024
	APIKeyGetFilesystemSecurityToken APIKey = 1025
	APIKeyInitWriter                 APIKey = 1026
	APIKeyCommitRemoteLogManifest    APIKey = 1027
	APIKeyNotifyRemoteLogOffsets     APIKey = 1028
	APIKeyNotifyKvSnapshotOffset     APIKey = 1029
	APIKeyCommitLakeTableSnapshot    APIKey = 1030
	APIKeyNotifyLakeTableOffset      APIKey = 1031
	APIKeyGetLakeSnapshot            APIKey = 1032
	APIKeyLimitScan                  APIKey = 1033
	APIKeyPrefixLookup               APIKey = 1034
	APIKeyGetDatabaseInfo            APIKey = 1035
	APIKeyCreatePartition            APIKey = 1036
	APIKeyDropPartition              APIKey = 1037
	APIKeyAuthenticate               APIKey = 1038
	APIKeyCreateAcls                 APIKey = 1039
	APIKeyListAcls                   APIKey = 1040
	APIKeyDropAcls                   APIKey = 1041
	APIKeyLakeTieringHeartbeat       APIKey = 1042
	APIKeyControlledShutdown         APIKey = 1043
	APIKeyAlterTable                 APIKey = 1044
	APIKeyDescribeClusterConfigs     APIKey = 1045
	APIKeyAlterClusterConfigs        APIKey = 1046
	APIKeyAddServerTag               APIKey = 1047
	APIKeyRemoveServerTag            APIKey = 1048
	APIKeyRebalance                  APIKey = 1049
	APIKeyListRebalanceProgress      APIKey = 1050
	APIKeyCancelRebalance            APIKey = 1051
	APIKeyPrepareLakeTableSnapshot   APIKey = 1052
	APIKeyRegisterProducerOffsets    APIKey = 1053
	APIKeyGetProducerOffsets         APIKey = 1054
	APIKeyDeleteProducerOffsets      APIKey = 1055
	APIKeyAcquireKvSnapshotLease     APIKey = 1056
	APIKeyReleaseKvSnapshotLease     APIKey = 1057
	APIKeyDropKvSnapshotLease        APIKey = 1058
	APIKeyGetTableStats              APIKey = 1059
)

type APIMetadata struct {
	Key          APIKey
	Name         string
	MinVersion   int16
	MaxVersion   int16
	Public       bool
	RequestName  string
	ResponseName string
}

var generatedAPIs = [...]APIMetadata{
	{APIKeyApiVersions, "API_VERSIONS", 0, 0, true, "ApiVersionsRequest", "ApiVersionsResponse"},
	{APIKeyCreateDatabase, "CREATE_DATABASE", 0, 0, true, "CreateDatabaseRequest", "CreateDatabaseResponse"},
	{APIKeyDropDatabase, "DROP_DATABASE", 0, 0, true, "DropDatabaseRequest", "DropDatabaseResponse"},
	{APIKeyListDatabases, "LIST_DATABASES", 0, 0, true, "ListDatabasesRequest", "ListDatabasesResponse"},
	{APIKeyDatabaseExists, "DATABASE_EXISTS", 0, 0, true, "DatabaseExistsRequest", "DatabaseExistsResponse"},
	{APIKeyCreateTable, "CREATE_TABLE", 0, 0, true, "CreateTableRequest", "CreateTableResponse"},
	{APIKeyDropTable, "DROP_TABLE", 0, 0, true, "DropTableRequest", "DropTableResponse"},
	{APIKeyGetTableInfo, "GET_TABLE_INFO", 0, 0, true, "GetTableInfoRequest", "GetTableInfoResponse"},
	{APIKeyListTables, "LIST_TABLES", 0, 0, true, "ListTablesRequest", "ListTablesResponse"},
	{APIKeyListPartitionInfos, "LIST_PARTITION_INFOS", 0, 0, true, "ListPartitionInfosRequest", "ListPartitionInfosResponse"},
	{APIKeyTableExists, "TABLE_EXISTS", 0, 0, true, "TableExistsRequest", "TableExistsResponse"},
	{APIKeyGetTableSchema, "GET_TABLE_SCHEMA", 0, 0, true, "GetTableSchemaRequest", "GetTableSchemaResponse"},
	{APIKeyGetMetadata, "GET_METADATA", 0, 0, true, "MetadataRequest", "MetadataResponse"},
	{APIKeyUpdateMetadata, "UPDATE_METADATA", 0, 0, false, "UpdateMetadataRequest", "UpdateMetadataResponse"},
	{APIKeyProduceLog, "PRODUCE_LOG", 0, 0, true, "ProduceLogRequest", "ProduceLogResponse"},
	{APIKeyFetchLog, "FETCH_LOG", 0, 0, true, "FetchLogRequest", "FetchLogResponse"},
	{APIKeyPutKv, "PUT_KV", 0, 1, true, "PutKvRequest", "PutKvResponse"},
	{APIKeyLookup, "LOOKUP", 0, 1, true, "LookupRequest", "LookupResponse"},
	{APIKeyNotifyLeaderAndIsr, "NOTIFY_LEADER_AND_ISR", 0, 0, false, "NotifyLeaderAndIsrRequest", "NotifyLeaderAndIsrResponse"},
	{APIKeyStopReplica, "STOP_REPLICA", 0, 0, false, "StopReplicaRequest", "StopReplicaResponse"},
	{APIKeyAdjustIsr, "ADJUST_ISR", 0, 0, false, "AdjustIsrRequest", "AdjustIsrResponse"},
	{APIKeyListOffsets, "LIST_OFFSETS", 0, 0, true, "ListOffsetsRequest", "ListOffsetsResponse"},
	{APIKeyCommitKvSnapshot, "COMMIT_KV_SNAPSHOT", 0, 0, false, "CommitKvSnapshotRequest", "CommitKvSnapshotResponse"},
	{APIKeyGetLatestKvSnapshots, "GET_LATEST_KV_SNAPSHOTS", 0, 0, true, "GetLatestKvSnapshotsRequest", "GetLatestKvSnapshotsResponse"},
	{APIKeyGetKvSnapshotMetadata, "GET_KV_SNAPSHOT_METADATA", 0, 0, true, "GetKvSnapshotMetadataRequest", "GetKvSnapshotMetadataResponse"},
	{APIKeyGetFilesystemSecurityToken, "GET_FILESYSTEM_SECURITY_TOKEN", 0, 0, true, "GetFileSystemSecurityTokenRequest", "GetFileSystemSecurityTokenResponse"},
	{APIKeyInitWriter, "INIT_WRITER", 0, 0, true, "InitWriterRequest", "InitWriterResponse"},
	{APIKeyCommitRemoteLogManifest, "COMMIT_REMOTE_LOG_MANIFEST", 0, 0, false, "CommitRemoteLogManifestRequest", "CommitRemoteLogManifestResponse"},
	{APIKeyNotifyRemoteLogOffsets, "NOTIFY_REMOTE_LOG_OFFSETS", 0, 0, false, "NotifyRemoteLogOffsetsRequest", "NotifyRemoteLogOffsetsResponse"},
	{APIKeyNotifyKvSnapshotOffset, "NOTIFY_KV_SNAPSHOT_OFFSET", 0, 0, false, "NotifyKvSnapshotOffsetRequest", "NotifyKvSnapshotOffsetResponse"},
	{APIKeyCommitLakeTableSnapshot, "COMMIT_LAKE_TABLE_SNAPSHOT", 0, 0, false, "CommitLakeTableSnapshotRequest", "CommitLakeTableSnapshotResponse"},
	{APIKeyNotifyLakeTableOffset, "NOTIFY_LAKE_TABLE_OFFSET", 0, 0, false, "NotifyLakeTableOffsetRequest", "NotifyLakeTableOffsetResponse"},
	{APIKeyGetLakeSnapshot, "GET_LAKE_SNAPSHOT", 0, 0, true, "GetLakeSnapshotRequest", "GetLakeSnapshotResponse"},
	{APIKeyLimitScan, "LIMIT_SCAN", 0, 0, true, "LimitScanRequest", "LimitScanResponse"},
	{APIKeyPrefixLookup, "PREFIX_LOOKUP", 0, 1, true, "PrefixLookupRequest", "PrefixLookupResponse"},
	{APIKeyGetDatabaseInfo, "GET_DATABASE_INFO", 0, 0, true, "GetDatabaseInfoRequest", "GetDatabaseInfoResponse"},
	{APIKeyCreatePartition, "CREATE_PARTITION", 0, 0, true, "CreatePartitionRequest", "CreatePartitionResponse"},
	{APIKeyDropPartition, "DROP_PARTITION", 0, 0, true, "DropPartitionRequest", "DropPartitionResponse"},
	{APIKeyAuthenticate, "AUTHENTICATE", 0, 0, true, "AuthenticateRequest", "AuthenticateResponse"},
	{APIKeyCreateAcls, "CREATE_ACLS", 0, 0, true, "CreateAclsRequest", "CreateAclsResponse"},
	{APIKeyListAcls, "LIST_ACLS", 0, 0, true, "ListAclsRequest", "ListAclsResponse"},
	{APIKeyDropAcls, "DROP_ACLS", 0, 0, true, "DropAclsRequest", "DropAclsResponse"},
	{APIKeyLakeTieringHeartbeat, "LAKE_TIERING_HEARTBEAT", 0, 0, false, "LakeTieringHeartbeatRequest", "LakeTieringHeartbeatResponse"},
	{APIKeyControlledShutdown, "CONTROLLED_SHUTDOWN", 0, 0, false, "ControlledShutdownRequest", "ControlledShutdownResponse"},
	{APIKeyAlterTable, "ALTER_TABLE", 0, 0, true, "AlterTableRequest", "AlterTableResponse"},
	{APIKeyDescribeClusterConfigs, "DESCRIBE_CLUSTER_CONFIGS", 0, 0, true, "DescribeClusterConfigsRequest", "DescribeClusterConfigsResponse"},
	{APIKeyAlterClusterConfigs, "ALTER_CLUSTER_CONFIGS", 0, 0, true, "AlterClusterConfigsRequest", "AlterClusterConfigsResponse"},
	{APIKeyAddServerTag, "ADD_SERVER_TAG", 0, 0, true, "AddServerTagRequest", "AddServerTagResponse"},
	{APIKeyRemoveServerTag, "REMOVE_SERVER_TAG", 0, 0, true, "RemoveServerTagRequest", "RemoveServerTagResponse"},
	{APIKeyRebalance, "REBALANCE", 0, 0, true, "RebalanceRequest", "RebalanceResponse"},
	{APIKeyListRebalanceProgress, "LIST_REBALANCE_PROGRESS", 0, 0, true, "ListRebalanceProgressRequest", "ListRebalanceProgressResponse"},
	{APIKeyCancelRebalance, "CANCEL_REBALANCE", 0, 0, true, "CancelRebalanceRequest", "CancelRebalanceResponse"},
	{APIKeyPrepareLakeTableSnapshot, "PREPARE_LAKE_TABLE_SNAPSHOT", 0, 0, false, "PrepareLakeTableSnapshotRequest", "PrepareLakeTableSnapshotResponse"},
	{APIKeyRegisterProducerOffsets, "REGISTER_PRODUCER_OFFSETS", 0, 0, true, "RegisterProducerOffsetsRequest", "RegisterProducerOffsetsResponse"},
	{APIKeyGetProducerOffsets, "GET_PRODUCER_OFFSETS", 0, 0, true, "GetProducerOffsetsRequest", "GetProducerOffsetsResponse"},
	{APIKeyDeleteProducerOffsets, "DELETE_PRODUCER_OFFSETS", 0, 0, true, "DeleteProducerOffsetsRequest", "DeleteProducerOffsetsResponse"},
	{APIKeyAcquireKvSnapshotLease, "ACQUIRE_KV_SNAPSHOT_LEASE", 0, 0, true, "AcquireKvSnapshotLeaseRequest", "AcquireKvSnapshotLeaseResponse"},
	{APIKeyReleaseKvSnapshotLease, "RELEASE_KV_SNAPSHOT_LEASE", 0, 0, true, "ReleaseKvSnapshotLeaseRequest", "ReleaseKvSnapshotLeaseResponse"},
	{APIKeyDropKvSnapshotLease, "DROP_KV_SNAPSHOT_LEASE", 0, 0, true, "DropKvSnapshotLeaseRequest", "DropKvSnapshotLeaseResponse"},
	{APIKeyGetTableStats, "GET_TABLE_STATS", 0, 0, true, "GetTableStatsRequest", "GetTableStatsResponse"},
}

func APIKeys() []APIMetadata {
	return append([]APIMetadata(nil), generatedAPIs[:]...)
}

func LookupAPIKey(key APIKey) (APIMetadata, bool) {
	index := int(key) - 1000
	if index < 0 || index >= len(generatedAPIs) {
		return APIMetadata{}, false
	}
	return generatedAPIs[index], true
}

func newRequestProto(key APIKey) proto.Message {
	switch key {
	case APIKeyApiVersions:
		return &ApiVersionsRequest{}
	case APIKeyCreateDatabase:
		return &CreateDatabaseRequest{}
	case APIKeyDropDatabase:
		return &DropDatabaseRequest{}
	case APIKeyListDatabases:
		return &ListDatabasesRequest{}
	case APIKeyDatabaseExists:
		return &DatabaseExistsRequest{}
	case APIKeyCreateTable:
		return &CreateTableRequest{}
	case APIKeyDropTable:
		return &DropTableRequest{}
	case APIKeyGetTableInfo:
		return &GetTableInfoRequest{}
	case APIKeyListTables:
		return &ListTablesRequest{}
	case APIKeyListPartitionInfos:
		return &ListPartitionInfosRequest{}
	case APIKeyTableExists:
		return &TableExistsRequest{}
	case APIKeyGetTableSchema:
		return &GetTableSchemaRequest{}
	case APIKeyGetMetadata:
		return &MetadataRequest{}
	case APIKeyUpdateMetadata:
		return &UpdateMetadataRequest{}
	case APIKeyProduceLog:
		return &ProduceLogRequest{}
	case APIKeyFetchLog:
		return &FetchLogRequest{}
	case APIKeyPutKv:
		return &PutKvRequest{}
	case APIKeyLookup:
		return &LookupRequest{}
	case APIKeyNotifyLeaderAndIsr:
		return &NotifyLeaderAndIsrRequest{}
	case APIKeyStopReplica:
		return &StopReplicaRequest{}
	case APIKeyAdjustIsr:
		return &AdjustIsrRequest{}
	case APIKeyListOffsets:
		return &ListOffsetsRequest{}
	case APIKeyCommitKvSnapshot:
		return &CommitKvSnapshotRequest{}
	case APIKeyGetLatestKvSnapshots:
		return &GetLatestKvSnapshotsRequest{}
	case APIKeyGetKvSnapshotMetadata:
		return &GetKvSnapshotMetadataRequest{}
	case APIKeyGetFilesystemSecurityToken:
		return &GetFileSystemSecurityTokenRequest{}
	case APIKeyInitWriter:
		return &InitWriterRequest{}
	case APIKeyCommitRemoteLogManifest:
		return &CommitRemoteLogManifestRequest{}
	case APIKeyNotifyRemoteLogOffsets:
		return &NotifyRemoteLogOffsetsRequest{}
	case APIKeyNotifyKvSnapshotOffset:
		return &NotifyKvSnapshotOffsetRequest{}
	case APIKeyCommitLakeTableSnapshot:
		return &CommitLakeTableSnapshotRequest{}
	case APIKeyNotifyLakeTableOffset:
		return &NotifyLakeTableOffsetRequest{}
	case APIKeyGetLakeSnapshot:
		return &GetLakeSnapshotRequest{}
	case APIKeyLimitScan:
		return &LimitScanRequest{}
	case APIKeyPrefixLookup:
		return &PrefixLookupRequest{}
	case APIKeyGetDatabaseInfo:
		return &GetDatabaseInfoRequest{}
	case APIKeyCreatePartition:
		return &CreatePartitionRequest{}
	case APIKeyDropPartition:
		return &DropPartitionRequest{}
	case APIKeyAuthenticate:
		return &AuthenticateRequest{}
	case APIKeyCreateAcls:
		return &CreateAclsRequest{}
	case APIKeyListAcls:
		return &ListAclsRequest{}
	case APIKeyDropAcls:
		return &DropAclsRequest{}
	case APIKeyLakeTieringHeartbeat:
		return &LakeTieringHeartbeatRequest{}
	case APIKeyControlledShutdown:
		return &ControlledShutdownRequest{}
	case APIKeyAlterTable:
		return &AlterTableRequest{}
	case APIKeyDescribeClusterConfigs:
		return &DescribeClusterConfigsRequest{}
	case APIKeyAlterClusterConfigs:
		return &AlterClusterConfigsRequest{}
	case APIKeyAddServerTag:
		return &AddServerTagRequest{}
	case APIKeyRemoveServerTag:
		return &RemoveServerTagRequest{}
	case APIKeyRebalance:
		return &RebalanceRequest{}
	case APIKeyListRebalanceProgress:
		return &ListRebalanceProgressRequest{}
	case APIKeyCancelRebalance:
		return &CancelRebalanceRequest{}
	case APIKeyPrepareLakeTableSnapshot:
		return &PrepareLakeTableSnapshotRequest{}
	case APIKeyRegisterProducerOffsets:
		return &RegisterProducerOffsetsRequest{}
	case APIKeyGetProducerOffsets:
		return &GetProducerOffsetsRequest{}
	case APIKeyDeleteProducerOffsets:
		return &DeleteProducerOffsetsRequest{}
	case APIKeyAcquireKvSnapshotLease:
		return &AcquireKvSnapshotLeaseRequest{}
	case APIKeyReleaseKvSnapshotLease:
		return &ReleaseKvSnapshotLeaseRequest{}
	case APIKeyDropKvSnapshotLease:
		return &DropKvSnapshotLeaseRequest{}
	case APIKeyGetTableStats:
		return &GetTableStatsRequest{}
	default:
		return nil
	}
}

func newResponseProto(key APIKey) proto.Message {
	switch key {
	case APIKeyApiVersions:
		return &ApiVersionsResponse{}
	case APIKeyCreateDatabase:
		return &CreateDatabaseResponse{}
	case APIKeyDropDatabase:
		return &DropDatabaseResponse{}
	case APIKeyListDatabases:
		return &ListDatabasesResponse{}
	case APIKeyDatabaseExists:
		return &DatabaseExistsResponse{}
	case APIKeyCreateTable:
		return &CreateTableResponse{}
	case APIKeyDropTable:
		return &DropTableResponse{}
	case APIKeyGetTableInfo:
		return &GetTableInfoResponse{}
	case APIKeyListTables:
		return &ListTablesResponse{}
	case APIKeyListPartitionInfos:
		return &ListPartitionInfosResponse{}
	case APIKeyTableExists:
		return &TableExistsResponse{}
	case APIKeyGetTableSchema:
		return &GetTableSchemaResponse{}
	case APIKeyGetMetadata:
		return &MetadataResponse{}
	case APIKeyUpdateMetadata:
		return &UpdateMetadataResponse{}
	case APIKeyProduceLog:
		return &ProduceLogResponse{}
	case APIKeyFetchLog:
		return &FetchLogResponse{}
	case APIKeyPutKv:
		return &PutKvResponse{}
	case APIKeyLookup:
		return &LookupResponse{}
	case APIKeyNotifyLeaderAndIsr:
		return &NotifyLeaderAndIsrResponse{}
	case APIKeyStopReplica:
		return &StopReplicaResponse{}
	case APIKeyAdjustIsr:
		return &AdjustIsrResponse{}
	case APIKeyListOffsets:
		return &ListOffsetsResponse{}
	case APIKeyCommitKvSnapshot:
		return &CommitKvSnapshotResponse{}
	case APIKeyGetLatestKvSnapshots:
		return &GetLatestKvSnapshotsResponse{}
	case APIKeyGetKvSnapshotMetadata:
		return &GetKvSnapshotMetadataResponse{}
	case APIKeyGetFilesystemSecurityToken:
		return &GetFileSystemSecurityTokenResponse{}
	case APIKeyInitWriter:
		return &InitWriterResponse{}
	case APIKeyCommitRemoteLogManifest:
		return &CommitRemoteLogManifestResponse{}
	case APIKeyNotifyRemoteLogOffsets:
		return &NotifyRemoteLogOffsetsResponse{}
	case APIKeyNotifyKvSnapshotOffset:
		return &NotifyKvSnapshotOffsetResponse{}
	case APIKeyCommitLakeTableSnapshot:
		return &CommitLakeTableSnapshotResponse{}
	case APIKeyNotifyLakeTableOffset:
		return &NotifyLakeTableOffsetResponse{}
	case APIKeyGetLakeSnapshot:
		return &GetLakeSnapshotResponse{}
	case APIKeyLimitScan:
		return &LimitScanResponse{}
	case APIKeyPrefixLookup:
		return &PrefixLookupResponse{}
	case APIKeyGetDatabaseInfo:
		return &GetDatabaseInfoResponse{}
	case APIKeyCreatePartition:
		return &CreatePartitionResponse{}
	case APIKeyDropPartition:
		return &DropPartitionResponse{}
	case APIKeyAuthenticate:
		return &AuthenticateResponse{}
	case APIKeyCreateAcls:
		return &CreateAclsResponse{}
	case APIKeyListAcls:
		return &ListAclsResponse{}
	case APIKeyDropAcls:
		return &DropAclsResponse{}
	case APIKeyLakeTieringHeartbeat:
		return &LakeTieringHeartbeatResponse{}
	case APIKeyControlledShutdown:
		return &ControlledShutdownResponse{}
	case APIKeyAlterTable:
		return &AlterTableResponse{}
	case APIKeyDescribeClusterConfigs:
		return &DescribeClusterConfigsResponse{}
	case APIKeyAlterClusterConfigs:
		return &AlterClusterConfigsResponse{}
	case APIKeyAddServerTag:
		return &AddServerTagResponse{}
	case APIKeyRemoveServerTag:
		return &RemoveServerTagResponse{}
	case APIKeyRebalance:
		return &RebalanceResponse{}
	case APIKeyListRebalanceProgress:
		return &ListRebalanceProgressResponse{}
	case APIKeyCancelRebalance:
		return &CancelRebalanceResponse{}
	case APIKeyPrepareLakeTableSnapshot:
		return &PrepareLakeTableSnapshotResponse{}
	case APIKeyRegisterProducerOffsets:
		return &RegisterProducerOffsetsResponse{}
	case APIKeyGetProducerOffsets:
		return &GetProducerOffsetsResponse{}
	case APIKeyDeleteProducerOffsets:
		return &DeleteProducerOffsetsResponse{}
	case APIKeyAcquireKvSnapshotLease:
		return &AcquireKvSnapshotLeaseResponse{}
	case APIKeyReleaseKvSnapshotLease:
		return &ReleaseKvSnapshotLeaseResponse{}
	case APIKeyDropKvSnapshotLease:
		return &DropKvSnapshotLeaseResponse{}
	case APIKeyGetTableStats:
		return &GetTableStatsResponse{}
	default:
		return nil
	}
}
