// Command protocolgen generates protocol metadata from pinned Apache Fluss inputs.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

const generatorVersion = "v0.1.0"

var apiPattern = regexp.MustCompile("(?m)^\\s*([A-Z_]+)\\((\\d+),\\s*(\\d+),\\s*(\\d+),\\s*(PUBLIC|PRIVATE)\\)[,;]?$")
var messagePattern = regexp.MustCompile("(?m)^message\\s+([A-Za-z0-9]+(?:Request|Response))\\s*\\{")

type api struct {
	enumName string
	key      int
	min      int
	max      int
	public   bool
	request  string
	response string
}

func main() {
	var inputs string
	var output string
	flag.StringVar(&inputs, "inputs", "third_party/apache-fluss", "pinned Apache Fluss input directory")
	flag.StringVar(&output, "output", "pkg/fmsg/api_keys_gen.go", "generated Go output")
	flag.Parse()

	apis, err := loadAPIs(inputs)
	if err != nil {
		fatal(err)
	}
	source, err := generate(apis)
	if err != nil {
		fatal(err)
	}
	if err := os.MkdirAll(filepath.Dir(output), 0o755); err != nil {
		fatal(err)
	}
	if err := os.WriteFile(output, source, 0o644); err != nil {
		fatal(err)
	}
}

func loadAPIs(inputs string) ([]api, error) {
	keySource, err := os.ReadFile(filepath.Join(inputs, "ApiKeys.java"))
	if err != nil {
		return nil, fmt.Errorf("read ApiKeys.java: %w", err)
	}
	protoSource, err := os.ReadFile(filepath.Join(inputs, "FlussApi.proto"))
	if err != nil {
		return nil, fmt.Errorf("read FlussApi.proto: %w", err)
	}

	messages := make(map[string]struct{})
	for _, match := range messagePattern.FindAllStringSubmatch(string(protoSource), -1) {
		messages[match[1]] = struct{}{}
	}

	var apis []api
	for _, match := range apiPattern.FindAllStringSubmatch(string(keySource), -1) {
		key, _ := strconv.Atoi(match[2])
		min, _ := strconv.Atoi(match[3])
		max, _ := strconv.Atoi(match[4])
		base := messageBase(match[1])
		request := base + "Request"
		response := base + "Response"
		if _, ok := messages[request]; !ok {
			return nil, fmt.Errorf("API %s has no %s in FlussApi.proto", match[1], request)
		}
		if _, ok := messages[response]; !ok {
			return nil, fmt.Errorf("API %s has no %s in FlussApi.proto", match[1], response)
		}
		apis = append(apis, api{
			enumName: match[1],
			key:      key,
			min:      min,
			max:      max,
			public:   match[5] == "PUBLIC",
			request:  request,
			response: response,
		})
	}
	if len(apis) != 60 {
		return nil, fmt.Errorf("expected 60 API keys, found %d", len(apis))
	}
	sort.Slice(apis, func(i, j int) bool { return apis[i].key < apis[j].key })
	for i, entry := range apis {
		if entry.key != 1000+i {
			return nil, fmt.Errorf("expected API key %d, found %d", 1000+i, entry.key)
		}
	}
	return apis, nil
}

func messageBase(enumName string) string {
	if base, ok := map[string]string{
		"API_VERSIONS":                  "ApiVersions",
		"GET_METADATA":                  "Metadata",
		"GET_FILESYSTEM_SECURITY_TOKEN": "GetFileSystemSecurityToken",
	}[enumName]; ok {
		return base
	}
	parts := strings.Split(strings.ToLower(enumName), "_")
	for i := range parts {
		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	return strings.Join(parts, "")
}

func generate(apis []api) ([]byte, error) {
	var output bytes.Buffer
	output.WriteString("// Code generated by protocolgen " + generatorVersion + "; DO NOT EDIT.\n")
	output.WriteString("// Source: Apache Fluss v0.9.1-incubating commit 6bf969f71af8d6f9cc37383ab89ae46a58b0e227.\n\n")
	output.WriteString("package fmsg\n\n")
	output.WriteString("type APIKey int16\n\n")
	output.WriteString("const (\n")
	for _, entry := range apis {
		fmt.Fprintf(&output, "\tAPIKey%s APIKey = %d\n", goName(entry.enumName), entry.key)
	}
	output.WriteString(")\n\n")
	output.WriteString("type APIMetadata struct {\n")
	output.WriteString("\tKey APIKey\n\tName string\n\tMinVersion int16\n\tMaxVersion int16\n\tPublic bool\n\tRequestName string\n\tResponseName string\n}\n\n")
	output.WriteString("var generatedAPIs = [...]APIMetadata{\n")
	for _, entry := range apis {
		fmt.Fprintf(&output, "\t{APIKey%s, %q, %d, %d, %t, %q, %q},\n", goName(entry.enumName), entry.enumName, entry.min, entry.max, entry.public, entry.request, entry.response)
	}
	output.WriteString("}\n\n")
	output.WriteString("func APIKeys() []APIMetadata {\n\treturn append([]APIMetadata(nil), generatedAPIs[:]...)\n}\n\n")
	output.WriteString("func LookupAPIKey(key APIKey) (APIMetadata, bool) {\n")
	output.WriteString("\tindex := int(key) - 1000\n\tif index < 0 || index >= len(generatedAPIs) { return APIMetadata{}, false }\n")
	output.WriteString("\treturn generatedAPIs[index], true\n}\n")
	return format.Source(output.Bytes())
}

func goName(enumName string) string {
	parts := strings.Split(strings.ToLower(enumName), "_")
	for i := range parts {
		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	return strings.Join(parts, "")
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "protocolgen:", err)
	os.Exit(1)
}
