name: Fluss 0.9.1 Integration

on:
  workflow_dispatch:
  schedule:
    - cron: '31 2 * * 3'

permissions:
  contents: read

jobs:
  live:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: 1.26.x
          check-latest: true
      - uses: go-task/setup-task@01a4adf9db2d14c1de7a560f09170b6e0df736aa # v2.1.0
        with:
          version: 3.51.1
      - run: task test:integration
