name: Security

on:
  push:
    branches:
      - main
  schedule:
    - cron: '17 3 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.0.1
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.0.0
        with:
          go-version: 1.26.x
          check-latest: true
      - uses: go-task/setup-task@01a4adf9db2d14c1de7a560f09170b6e0df736aa # v1.0.0
        with:
          version: 3.51.1
      - uses: aquasecurity/setup-trivy@81e514348e19b6112ce2a7e3ecbafe19c1e1f567 # v0.3.1
        with:
          version: v0.72.0
      - run: task security
